name: Latest image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/lucasvs/docker-asterisk:latest
        docker push ghcr.io/lucasvs/docker-asterisk:latest
